android/src/main/kotlin/com/jarvan/fluwx/utils/WeChatThumbnailUtil.java

修改url路径解析后缀错误问题。

---

.vscode/cscope_conf.json
ios/Classes/FluwxPlugin.m
ios/Classes/constants/FluwxMethods.h
ios/Classes/constants/FluwxMethods.m
ios/Classes/handler/FluwxLaunchMiniProgramHandler.m
ios/Classes/public/FluwxLaunchMiniProgramHandler.h
lib/src/fluwx_class.dart
lib/src/models/wechat_launchminiprogram_model.dart
lib/src/models/wechat_response.dart
lib/src/wechat_type.dart

add WeChatLaunchMiniProgram

---

android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/constant/WeChatPluginMethods.java
android/src/main/kotlin/com/jarvan/fluwx/handler/FluwxResponseHandler.kt
android/src/main/kotlin/com/jarvan/fluwx/handler/FluwxSubscribeMsgHandler.kt
example/lib/main.dart
example/lib/subscribe_message_page.dart
ios/Classes/FluwxPlugin.m
ios/Classes/handler/FluwxSubscribeMsgHandler.m
ios/Classes/public/FluwxSubscribeMsgHandler.h
ios/Classes/wechat/FluwxResponseHandler.m
lib/src/fluwx_iml.dart
lib/src/models/wechat_response.dart

参考 [官方文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1500434436_aWfqW&token=&lang=zh_CN)

一次性订阅消息的api

---

README.md
README_CN.md
android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/constant/WeChatPluginMethods.java
android/src/main/kotlin/com/jarvan/fluwx/handler/FluwxAutoDeductHandler.kt
doc/AUTO_DEDUCT.md
doc/AUTO_DEDUCT_CN.md
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
example/lib/sign_auto_deduct_page.dart
ios/Classes/FluwxPlugin.m
ios/Classes/handler/FluwxAutoDeductHandler.m
ios/Classes/public/FluwxAutoDeductHandler.h
ios/Classes/public/WXApiObject.h
ios/README.txt
lib/src/fluwx_iml.dart

 sign auto-deduct

---

example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner/AppDelegate.h
example/ios/Runner/AppDelegate.m
ios/Classes/public/WXApi.h
ios/Classes/public/WXApiObject.h
ios/Classes/public/WechatAuthSDK.h
ios/fluwx.podspec

Revert "Use ios sdk from pod"

---

example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
ios/Classes/FluwxPlugin.m
ios/Classes/handler/FluwxAutoDeductHandler.m
ios/Classes/handler/FluwxShareHandler.m
ios/Classes/handler/NSStringWrapper.h
ios/Classes/handler/NSStringWrapper.m
ios/Classes/public/WXApi.h
ios/Classes/public/WXApiObject.h
ios/Classes/public/WXApiRequestHandler.h
ios/Classes/wechat/FluwxResponseHandler.m
pubspec.yaml

Fix https://github.com/OpenFlutter/fluwx/issues/178.

Remove iOS warnings when debug, fix issue/178

---

ios/Classes/handler/FluwxShareHandler.m
ios/Classes/handler/FluwxWXApiHandler.m
ios/Classes/helper/FluwxStringUtil.h
ios/Classes/helper/FluwxStringUtil.m
ios/Classes/public/FluwxAuthHandler.h
ios/Classes/public/FluwxLaunchMiniProgramHandler.h
ios/Classes/public/FluwxPaymentHandler.h
ios/Classes/public/FluwxShareHandler.h
ios/Classes/wechat/FluwxResponseHandler.m
ios/Classes/wechat/WXApiRequestHandler.m

StringUtil太通用了，可能会与ios的三方库和代码发生类名重复的冲突

StringUtil renamed to FluwxStringUtil

---

ios/Classes/FluwxShareHandler.m

fix crash bug when hdImagePath is NSNull

Fix crash bug when hdImagePath is NSNull

---

android/src/main/kotlin/com/jarvan/fluwx/io/WeChatImages.kt

String need to be converted to File

Fix crash when android share image file

---

ios/Classes/FluwxAuthHandler.h
ios/Classes/FluwxResponseHandler.h
ios/Classes/FluwxResponseHandler.m
ios/Classes/SendMessageToWXReq+requestWithTextOrMediaMessage.h
ios/Classes/WXApiRequestHandler.h
ios/Classes/WXApiRequestHandler.m
ios/Classes/WXMediaMessage+messageConstruct.h

change import mode to support generate_multiple_pod_projects

refactor：use modular  import

---

doc/BASIC_KNOWLEDGE.md
doc/BASIC_KNOWLEDGE_CN.md
doc/QA_CN.md

根据群友们常问的问题，更新了 basic 和 QA 文档；修改了 QA 文档格式。

根据群友们常问的问题，更新了basic和QA文档

---

android/src/main/AndroidManifest.xml
android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/handlers/FluwxRequestHandler.kt
android/src/main/kotlin/com/jarvan/fluwx/wxapi/FluwxWXEntryActivity.kt
example/pubspec.lock
lib/src/response/wechat_response.dart

#316 
微信打开app后会打开一个空白页面，原因还不清楚，并且在冷启动时获取不到回调，拿不到相关参数。

微信开放标签打开App时获取信息（安卓）

---

lib/src/response/wechat_response.dart

bugfix: 微信登录没回调bug修复

---

android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/handlers/FluwxRequestHandler.kt
example/lib/main.dart
example/pubspec.lock
ios/Classes/FluwxPlugin.m
lib/src/fluwx_iml.dart

主动拉取extMsg

---

ios/Classes/FluwxResponseHandler.m

fixed crash when HK wallet business webview response nil in result

fixed HK wallet response crashed

---

example/android/app/src/main/AndroidManifest.xml
example/android/gradle.properties
example/pubspec.lock
example/pubspec.yaml
pubspec.lock

updated dart to latest stable null safety version
removed unused setting in gradle.properties
fixed #372

fixed #372

---

android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/handlers/WXAPiHandler.kt
example/lib/main.dart
ios/Classes/FluwxPlugin.m
lib/src/fluwx_iml.dart
lib/src/wechat_enums.dart

因为之前测试图片的问题，一直手动添加这个api; 看到你们一直没有添加这个东西，就加上了

feat: 增加微信的日志开关

---

android/src/main/kotlin/com/jarvan/fluwx/FluwxPlugin.kt
android/src/main/kotlin/com/jarvan/fluwx/handlers/FluwxResponseHandler.kt
android/src/main/kotlin/com/jarvan/fluwx/utils/WXApiUtils.java
ios/Classes/FluwxPlugin.m
ios/Classes/FluwxResponseHandler.m
ios/Classes/WXApiRequestHandler.h
ios/Classes/WXApiRequestHandler.m
lib/src/fluwx_iml.dart
lib/src/response/wechat_response.dart

返回 
[{
"card_id": "candid",
"encrypt_code": "encryptCode",
"app_id": "appId"
}]

增加打开微信卡包（发票）的功能（Android & IOS）

---

ios/Classes/FluwxPlugin.m

fix runnable

---

ios/Resources/PrivacyInfo.xcprivacy

By: https://github.com/flutter/flutter/issues/131940#issuecomment-2010097142

Update iOS privacy manifests file

---

example/pubspec.yaml

文档注释修改
fix : https://github.com/OpenFlutter/fluwx/issues/636

Update  pubspec.yaml

---

CHANGELOG.md
ios/Classes/FluwxPlugin.m
pubspec.yaml

- Fixes https://github.com/OpenFlutter/fluwx/issues/650
- Fixes https://github.com/OpenFlutter/fluwx/issues/647

Fix thumbnail issues on iOS

---

ios/Classes/FluwxDelegate.m
ios/Classes/FluwxPlugin.m
ios/Classes/FluwxStringUtil.m
ios/Classes/ThumbnailHelper.h
ios/Classes/ThumbnailHelper.m
ios/Classes/public/FluwxDelegate.h

🔥 Remove thumbnail and format files

---

CHANGELOG.md
ios/fluwx.podspec
ios/wechat_setup.rb
pubspec.yaml

- Cherry-pick #659
- Cherry-pick #663

Improve pod scripts

---

.github/workflows/publish.yml

add automated publishing

---

ios/wechat_setup.rb

🐛 Do not append empty associate domains

---

doc/SHARE_CN.md
ohos/oh-package.json5
ohos/src/main/ets/components/plugin/handlers/FluwxShareHandler.ets

增加鸿蒙分享网页和小程序，微信sdk升级1.0.6

---

ohos/oh-package.json5
ohos/src/main/ets/components/plugin/FluwxPlugin.ets

upgrade wechat sdk to 1.0.11
add onWXLaunchFromWX

upgrade wechat sdk ohos

---

ios/Classes/FluwxPlugin.m

Fix type error in `isSupportOpenBusinessView` on iOS
